In [2]:
from numpy import *

In [8]:
arr = array([1,2,3,4,5])

In [9]:
print(arr)

[1 2 3 4 5]


In [5]:
arr = linspace(0,15,10) #between 0-16 it will take 10 values

In [6]:
print(arr)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.         11.66666667 13.33333333 15.        ]


In [17]:
arr = arange(1,15,2)

In [18]:
print(arr)

[ 1  3  5  7  9 11 13]


In [19]:
arr = logspace(1,40,5)

In [20]:
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [22]:
print('%.2f' %arr[2])

316227766016837943296.00


In [5]:
arr = zeros(5)

In [6]:
print(arr)

[0. 0. 0. 0. 0.]


In [27]:
arr = ones(2,int)

In [28]:
print(arr)

[1 1]


In [47]:
from array import *
arr = array('i',[2,5,4,8])

In [48]:
print(arr)

array('i', [2, 5, 4, 8])


In [58]:
from numpy import *
arr = array([2,5,3,8])
arr = arr + 5

In [60]:
print(arr)

[ 7 10  8 13]


In [61]:
arr2 = array([2,4,5,7])
rarr = arr + arr2

In [62]:
print(rarr)

[ 9 14 13 20]


In [63]:
print(sin(arr))

[ 0.6569866  -0.54402111  0.98935825  0.42016704]


In [64]:
print(log(arr))

[1.94591015 2.30258509 2.07944154 2.56494936]


In [65]:
print(sqrt(arr))

[2.64575131 3.16227766 2.82842712 3.60555128]


In [66]:
print(sum(arr))

38


In [67]:
print(min(arr))

7


In [68]:
print(max(arr))

13


In [69]:
print(concatenate([arr,arr2]))

[ 7 10  8 13  2  4  5  7]


In [72]:
#copying an array
#shallow copy : when we change the value of one array ,others array's value will automatically change
#this only cahnge the address
arr = array([2,5,3,8])
arr2 = arr.view()

In [75]:
print(arr)
print(arr2)
id(arr)

[2 5 3 8]
[2 5 3 8]


1754241767984

In [76]:
id(arr2)

1754241768624

In [77]:
#deep copy : the copied array is not dependent on the previous array
arr2 = arr.copy()

In [78]:
print(arr2)

[2 5 3 8]


In [83]:
arr[0] = 4

In [84]:
print(arr)
print(arr2)

[4 5 3 8]
[2 5 3 8]


In [16]:
print('the number is {:.2f}'.format(arr[2]))

the number is 3.33


In [14]:
arr[2]

3.3333333333333335

In [15]:
round(arr[2],2)

3.33