In [2]:
from numpy import *

In [3]:
arr = array([[1,2,3],[5,7,8]])

In [4]:
print(arr)

[[1 2 3]
 [5 7 8]]


In [5]:
print(arr.ndim) # how many dimention

2


In [6]:
print(arr.shape)

(2, 3)


In [7]:
print(arr.size)

6


In [8]:
arr2  = arr.flatten()

In [9]:
print(arr2) #convert a two dimentional array to one dientional array

[1 2 3 5 7 8]


In [15]:
arr3 = arr2.reshape(3,2) #one dimention to two dimention

In [16]:
print(arr3)

[[1 2]
 [3 5]
 [7 8]]


In [18]:
arr4 = arr.reshape(2,1,3) # create a 3d array

In [19]:
print(arr4) 

[[[1 2 3]]

 [[5 7 8]]]


In [20]:
m = matrix(arr)

In [21]:
print(m)

[[1 2 3]
 [5 7 8]]


In [26]:
m1 = matrix('1 2 3; 6 4 5; 2 1 4')

In [27]:
print(diagonal(m1))

[1 4 4]


In [28]:
print(m1.min())

1


In [29]:
m2 = matrix('1 5 3; 8 7 2; 7 4 4')

In [32]:
m = m1*m2

In [33]:
print(m)

[[38 31 19]
 [73 78 46]
 [38 33 24]]
